// Compile loops into the context file your agent already reads.
// The point of owning the context: a model switch is a recompile, not a re-teach.

import fs from 'node:fs';
import path from 'node:path';
import { ACTIONS } from './loop.js';

export const TARGETS = {
  claude: { file: 'CLAUDE.md', label: 'Claude Code' },
  agents: { file: 'AGENTS.md', label: 'AGENTS.md (Codex, Cursor, Zed, …)' },
  cursor: { file: path.join('.cursor', 'rules', 'docket.mdc'), label: 'Cursor rules' },
  raw: { file: null, label: 'stdout' },
};

const BEGIN = '<!-- docket:begin — generated by `docket compile`, do not edit by hand -->';
const END = '<!-- docket:end -->';

// Loop prose is rendered verbatim into a file we later re-parse by marker,
// so the markers must never appear in rendered content. A zero-width space
// after "docket" keeps quoted markers readable but inert.
function neutralizeMarkers(text) {
  return text.replace(/<!--\s*docket:/g, '<!-- docket​:');
}

function bulletList(items, indent = '') {
  return items.map((i) => `${indent}- ${i}`).join('\n');
}

// One source of truth for how a warrant reads, shared by `docket show`,
// the compiler, and the MCP context tool — the human must review the same
// rules the agent operates under.
export function warrantLines(loop) {
  const lines = [];
  for (const action of ACTIONS) {
    const list = loop.warrant[action];
    lines.push({
      label: action,
      text: list.length ? list.join('; ') : '(nothing — ask first)',
      kind: 'action',
    });
  }
  if (loop.warrant.ask.length) {
    lines.push({ label: 'ask', text: loop.warrant.ask.join('; '), kind: 'ask' });
  }
  if (loop.warrant.never.length) {
    lines.push({ label: 'never', text: loop.warrant.never.join('; '), kind: 'never' });
  }
  return lines;
}

export function renderLoop(loop) {
  const lines = [];
  lines.push(`### Loop: ${loop.name}`);
  if (loop.description) lines.push('', `*${loop.description}*`);

  if (loop.brief) {
    lines.push('', '**Brief — know this before you start:**', '', loop.brief);
  }
  if (loop.procedure) {
    lines.push('', '**Procedure — how this work is done:**', '', loop.procedure);
  }

  lines.push('', '**Warrant — what you may do on your own:**', '');
  for (const row of warrantLines(loop)) {
    const label =
      row.kind === 'ask' ? 'always ask before' : row.kind === 'never' ? 'never, even with approval' : row.label;
    lines.push(`- ${label}: ${row.text}`);
  }
  lines.push(
    '',
    'Anything not listed above requires asking a human first. Silence is never permission.'
  );

  if (loop.reserved.length) {
    lines.push('', '**Reserved — stays human, do not touch:**', '', bulletList(loop.reserved));
  }

  if (loop.record.length) {
    lines.push(
      '',
      '**Record — when you finish (or stop), report:**',
      '',
      bulletList(loop.record)
    );
  }
  return neutralizeMarkers(lines.join('\n'));
}

export function renderBlock(loops) {
  const body = loops.map(renderLoop).join('\n\n---\n\n');
  const header = [
    '## Docket loops',
    '',
    'These loops define what you should remember, how the work happens, what you',
    'may do on your own, where you must stop, and what evidence you owe. Boundaries',
    'are not suggestions. When the warrant says ask, stop and ask.',
  ].join('\n');
  return `${BEGIN}\n${header}\n\n${body}\n${END}`;
}

// Locate the managed block: first BEGIN at a line start, LAST END at a line
// start. Content is marker-neutralized at render time, so a matching END is
// always a real one.
function findBlock(text) {
  const beginRe = /^<!-- docket:begin[^\n]*-->/m;
  const beginMatch = beginRe.exec(text);
  if (!beginMatch) return null;
  const endIdx = text.lastIndexOf(`\n${END}`);
  if (endIdx === -1 || endIdx < beginMatch.index) {
    throw new Error(
      `found a docket:begin marker without a matching docket:end — the file was ` +
        `edited by hand inside the managed block. Fix or remove the block, then recompile.`
    );
  }
  return { start: beginMatch.index, end: endIdx + 1 + END.length };
}

export function compileToFile(rootDir, target, loops) {
  const spec = TARGETS[target];
  if (!spec || !spec.file) throw new Error(`target "${target}" cannot be written to a file`);
  const filePath = path.join(rootDir, spec.file);
  const block = renderBlock(loops);
  let existing = '';
  if (fs.existsSync(filePath)) existing = fs.readFileSync(filePath, 'utf8');

  let next;
  const found = findBlock(existing);
  if (found) {
    next = existing.slice(0, found.start) + block + existing.slice(found.end);
  } else if (existing.trim()) {
    next = existing.replace(/\s*$/, '\n\n') + block + '\n';
  } else {
    next = block + '\n';
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, next);
  return filePath;
}
